# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.3

builder:
  image: jax-gangscheduling-job
  context: gangscheduling-demo/jax-gangscheduling-demo
  dockerfile: ./Dockerfile

spec:
  operator: jax
  image: jax-gangscheduling-job
  command: "python -u example_multihost_pmap.py"

  types:
    worker:
      count: 2
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
