# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.3

builder:
  image: pytorch-gangscheduling-job
  context: gangscheduling-demo/pytorch-gangscheduling-demo
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: pytorch-gangscheduling-job
  command: "python -u example_ddp.py"

  types:
    worker:
      count: 2
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
